### ISSUE TITLE
Labels for VOC 

### ISSUE THREAD

**Issue by akmaralAW** [sud0301/semisup-semseg#11]
Hello !

Good job ! Thanks for making it available. 

I was wondering what is the purpose of using SegmentationClassAug  as g.t labels instead of SegmentationClass ? 

Akmaral

**Comment by sud0301** [comment]
SegmentationClassAug contains extra (9118) images from Segmentation Boundary Dataset (SBD).

**Comment by akmaralAW** [comment]
thanks !
