### ISSUE TITLE
about Multi-Label Mean-Teacher branch

### ISSUE THREAD

**Issue by Lufei-github** [sud0301/semisup-semseg#3]
I don't exactly understand how adapt the Mean-teacher code to our segmentation code.So,can you explain it in detail or release the segment code with Mean-teacher model？Thanks!!!

**Comment by lxtGH** [comment]
@sud0301 Hi! Could you provide more details on Mean-teacher code? It is very interesting parts of the paper.

**Comment by k-fujimt** [comment]
@sud0301 I'm also waiting for your detailed explanation about the MLMT branch. Especially, I'm confused about following description:
> add Sigmoid activation for multi-label classification.
and 
> Use Binary Cross Entropy loss fucntion instead of multi-class Cross entropy.

In my understanding, the mean-teacher model in the referred repository performs the multi-label classification, therefore I don't think any changes other than the number of classes are required.
Could you explain about these modification?
Or, could you provide your code of MTML branch?

**Comment by mra1a** [comment]
@sud0301 Hi! Could you release the segment code with Mean-teacher model? Tanks!!!

**Comment by tsrobcvai** [comment]
Hi! Could you provide more details on Mean-teacher code? I am very interested in it @sud0301 @Lufei-github @mra1a

**Comment by sud0301** [comment]
Hi all, 
mean-teacher code/MLMT branch has been updated.

**Comment by whistlefancy** [comment]
> 大家好，
> 均值教师代码/ MLMT分支已更新。

Thanks you ! sir, That's very kind of you!

**Comment by tsrobcvai** [comment]
Thanks you ! sir, That's very kind of you!

> Hi all,
> mean-teacher code/MLMT branch has been updated.
