### ISSUE TITLE
MSCOCO pretrained weights and training script?

### ISSUE THREAD

**Issue by euwern** [sud0301/semisup-semseg#6]
Hey, thank you for sharing your code. In your paper, you report the numbers with pre-training on MS-COCO. Can you share the pre-trained weights for MSCOCO and also the training script, if the hyperparameters are different?

**Comment by sud0301** [comment]
You can find the COCO pre-trained weights [here](http://vllab1.ucmerced.edu/~whung/adv-semi-seg/resnet101COCO-41f33a49.pth) 
Hyperparameters are the same.

**Comment by euwern** [comment]
Thank you very much for sharing the weights.
